### ISSUE TITLE
[Doubt] process Not found

### ISSUE THREAD

**Issue by pedringcoding** [crim-ca/weaver#309] opened 2021-09-02 09:15 UTC
Hello,

I try execute the cycle to throw some in CWLTool from swagger and using default configuration in `~/master`.

I see the next steps:

1. I have a weaver app deployed in docker using the `docker-compose.smoke-test.yml` with some changes needed to file performance:

```yml
version: "3.4"

services:
  mongodb:
    image: mongo:3.6.0
    container_name: smoke_test_mongodb
    # mongodb crash with permission denied errors if the command is not overridden like this
    command: bash -c 'chown -R mongodb:mongodb /data && chmod -R 755 /data && mongod --bind_ip_all'
    restart: "no"

  manager:
    image: pavics/weaver:latest-manager
    container_name: smoke_test_manager
    environment:
      FORWARDED_ALLOW_IPS: "*"
    links:
      - mongodb
    ports:
      - "4001:4001"
    volumes:
      - ../../config/weaver.ini:/opt/local/src/weaver/config/weaver.ini
    networks:
      - default
    restart: "no"

  worker:
    image: pavics/weaver:latest-worker
    container_name: smoke_test_worker
    links:
      - mongodb
    volumes:
      - ../../config/weaver.ini:/opt/local/src/weaver/config/weaver.ini
    restart: "no"
```
I run the next command line:
```cmd
docker-compose -f docker-compose.smoke-test.yml up
```

2. I pattern followed to the generate files. See: [Examples](https://github.com/crim-ca/weaver/blob/master/docs/source/examples.rst)

3. I can check if process, HELLOWORD, is registered locally. Efectly, It isn't registered yet. Eg:

Request [GET](http://localhost:4001/processes/HELLOWORLD)
Response: 404
```json
{
  "description": "The resource could not be found. Process with ID 'HELLOWORLD' does not exist.",
  "code": "Not Found",
  "error": {
    "code": 404,
    "status": "404 Not Found"
  }
}
```

4. I'm prepare `DesployProcess_HELLOWORLD.json` to register a basic local process. I using the first example CWL in [commoncwl](https://www.commonwl.org/user_guide/02-1st-example/index.html). Eg:

Request [POST](http://localhost:4001/Processes)
Request body:
```json
{
  "processDescription": {
    "process": {
      "id": "HELLOWORLD",
      "title": "hello world application",
      "abstract": "The test application to display message",
      "visibility": "public"
    }
  },
  "executionUnit": [
    {
      "unit": {
        "cwlVersion": "v1.0",
        "class": "CommandLineTool",
        "baseCommand": "echo",
        "inputs": {
          "message": {
            "type": "string",
            "inputBinding": {
              "position": 1
            }
          }
        },
        "outputs": []
      }
    }
  ],
  "deploymentProfileName": "http://www.opengis.net/profiles/eoc/workflow"
}
```
Response: 201
```json
{
  "processSummary": {
    "keywords": [
      "application"
    ],
    "metadata": [],
    "title": "hello world application",
    "abstract": "The test application to display message",
    "id": "HELLOWORLD",
    "jobControlOptions": [
      "async-execute"
    ],
    "outputTransmission": [],
    "processDescriptionURL": "http://localhost:4001/processes/HELLOWORLD"
  },
  "deploymentDone": true
}
```

5. I can check if process, HELLOWORD, is registered locally. Efectly, It is registered. Eg:

Request [GET](http://localhost:4001/Processes/HELLOWORLD)
Response: 400
```json
{
  "process": {
    "keywords": [
      "application"
    ],
    "metadata": [],
    "title": "hello world application",
    "abstract": "The test application to display message",
    "id": "HELLOWORLD",
    "executeEndpoint": "http://localhost:4001/processes/HELLOWORLD/jobs",
    "inputs": [
      {
        "id": "message",
        "minOccurs": 1,
        "maxOccurs": 1
      }
    ],
    "outputs": [],
    "visibility": "public"
  },
  "jobControlOptions": [
    "async-execute"
  ]
}
```

6. I'm prepare `Execute_HELLOWORLD.json` to execute a process registered locally. Eg:

Request [POST](http://localhost:4001/Processes/HELLOWORLD/execution)
Request body:
```json
{
  "inputs": [
    {
      "id": "message",
      "data": "Hello world!"
    }
  ],
  "outputs": [],
  "mode": "sync",
  "response": "document"
}
```
Response: 404
```json
{
  "description": "The resource could not be found. /processes/HELLOWORLD/execution.",
  "code": "Not Found",
  "error": {
    "code": 404,
    "status": "404 Not Found"
  }
}
```
I can't down weaver level trace at TRACE.
So, Weaver trace at DEBUG level only throw:
```
smoke_test_manager | [2021-08-31 19:09:00,706] WARNING  [MainThread][weaver.tweens] Handled request exception:
smoke_test_manager |   Cause:  [POST http://localhost:4001/processes/HELLOWORLD/execution]
smoke_test_manager |   Raised: [(HTTPNotFound) <404> /processes/HELLOWORLD/execution]
```

What can missing me to complete execution step for this basic example?

- OS: Docker Windows (Hyper-V)
- Browser: Chrome
- Instance: EMS and http://localhost:4001/swagger
- Version: 3.5.0

Thanks for all,
Best regards

**Comment by pedringcoding** [comment] 2021-09-02 15:43
I tried again with solution purpose from https://github.com/crim-ca/weaver/issues/290#issuecomment-911767118

I have de same result

**Comment by fmigneault** [comment] 2021-09-02 15:51
Can you retry execution, but using this method instead? 
`POST http://localhost:4001/processes/HELLOWORLD/jobs`

If that works, I might have an idea of the cause of the problem.

**Comment by pedringcoding** [comment] 2021-09-02 17:29
I needed change `mode` attribute to `async`. The other mode:
Response: 501
```json
{
  "description": "Execution mode 'sync' not supported.",
  "code": "Not Implemented",
  "error": {
    "code": 501,
    "status": "501 Not Implemented"
  }
}
```

I tried again send [POST](http://localhost:4001/Processes/HELLOWORLD/jobs) request.
Request body:
```json
{
  "inputs": [
    {
      "id": "message",
      "data": "Hello world!"
    }
  ],
  "outputs": [],
  "mode": "async",
  "response": "document"
}
```
Response: 201
```json
{
  "jobID": "95291ce5-2ac8-4558-a0ca-d16ebe36c08a",
  "processID": "HELLOWORLD",
  "status": "accepted",
  "location": "http://localhost:4001/processes/HELLOWORLD/jobs/95291ce5-2ac8-4558-a0ca-d16ebe36c08a"
}
```

Weaver trace at DEBUG level throw:
```log
mongodb         | 2021-09-02T17:19:27.067+0000 I NETWORK  [thread1] connection accepted from 172.19.0.3:42762 #23 (11 connections now open)
mongodb         | 2021-09-02T17:19:27.069+0000 I NETWORK  [conn23] received client metadata from 172.19.0.3:42762 conn23: { driver: { name: "PyMongo", version: "3.12.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.10.25-linuxkit" }, platform: "CPython 3.7.11.final.0" }
mongodb         | 2021-09-02T17:19:27.074+0000 I NETWORK  [thread1] connection accepted from 172.19.0.3:42764 #24 (12 connections now open)
mongodb         | 2021-09-02T17:19:27.079+0000 I NETWORK  [conn24] received client metadata from 172.19.0.3:42764 conn24: { driver: { name: "PyMongo", version: "3.12.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.10.25-linuxkit" }, platform: "CPython 3.7.11.final.0" }
mongodb         | 2021-09-02T17:19:27.113+0000 I -        [conn23] end connection 172.19.0.3:42762 (12 connections now open)
mongodb         | 2021-09-02T17:19:27.113+0000 I -        [conn24] end connection 172.19.0.3:42764 (11 connections now open)
mongodb         | 2021-09-02T17:19:27.126+0000 I NETWORK  [thread1] connection accepted from 172.19.0.3:42766 #25 (11 connections now open)
mongodb         | 2021-09-02T17:19:27.129+0000 I NETWORK  [conn25] received client metadata from 172.19.0.3:42766 conn25: { driver: { name: "PyMongo", version: "3.12.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.10.25-linuxkit" }, platform: "CPython 3.7.11.final.0" }
mongodb         | 2021-09-02T17:19:27.132+0000 I NETWORK  [thread1] connection accepted from 172.19.0.3:42768 #26 (12 connections now open)
mongodb         | 2021-09-02T17:19:27.133+0000 I NETWORK  [conn26] received client metadata from 172.19.0.3:42768 conn26: { driver: { name: "PyMongo", version: "3.12.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.10.25-linuxkit" }, platform: "CPython 3.7.11.final.0" }
weaver-api      | [2021-09-02 17:19:27,142] WARNING  [MainThread][py.warnings] /opt/local/src/weaver/weaver/utils.py:307: TimeZoneInfoAlreadySetWarning: tzinfo already set
weaver-api      |   warnings.warn("tzinfo already set", TimeZoneInfoAlreadySetWarning)
weaver-api      |
mongodb         | 2021-09-02T17:19:27.232+0000 I NETWORK  [thread1] connection accepted from 172.19.0.3:42770 #27 (13 connections now open)
mongodb         | 2021-09-02T17:19:27.233+0000 I NETWORK  [conn27] received client metadata from 172.19.0.3:42770 conn27: { driver: { name: "PyMongo", version: "3.12.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.10.25-linuxkit" }, platform: "CPython 3.7.11.final.0" }
mongodb         | 2021-09-02T17:19:27.236+0000 I NETWORK  [thread1] connection accepted from 172.19.0.3:42772 #28 (14 connections now open)
mongodb         | 2021-09-02T17:19:27.239+0000 I NETWORK  [conn28] received client metadata from 172.19.0.3:42772 conn28: { driver: { name: "PyMongo", version: "3.12.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.10.25-linuxkit" }, platform: "CPython 3.7.11.final.0" }
mongodb         | 2021-09-02T17:19:27.257+0000 I -        [conn26] end connection 172.19.0.3:42768 (14 connections now open)
mongodb         | 2021-09-02T17:19:27.258+0000 I -        [conn25] end connection 172.19.0.3:42766 (13 connections now open)
weaver-worker   | [2021-09-02 17:19:27,778] INFO     [MainThread][celery.worker.strategy] Received task: weaver.processes.execution.execute_process[4e334dff-b739-4e1e-9c0e-c81b858ab6f5]
weaver-worker   | [2021-09-02 17:19:27,789] INFO     [MainThread][weaver.wps.utils] Initial load of internal Weaver WPS configuration.
weaver-worker   | [2021-09-02 17:19:27,790] INFO     [MainThread][PYWPS] loading configuration
weaver-worker   | [2021-09-02 17:19:27,807] INFO     [MainThread][PYWPS] No configuration files loaded. Using default values
weaver-worker   | [2021-09-02 17:19:27,826] ERROR    [MainThread][celery.app.trace] Task weaver.processes.execution.execute_process[4e334dff-b739-4e1e-9c0e-c81b858ab6f5] raised unexpected: FileNotFoundError(2, 'No such file or directory')
weaver-worker   | Traceback (most recent call last):
weaver-worker   |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
weaver-worker   |     R = retval = fun(*args, **kwargs)
weaver-worker   |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
weaver-worker   |     return self.run(*args, **kwargs)
weaver-worker   |   File "/opt/local/src/weaver/weaver/processes/execution.py", line 74, in execute_process
weaver-worker   |     load_pywps_config(settings)
weaver-worker   |   File "/opt/local/src/weaver/weaver/wps/utils.py", line 318, in load_pywps_config
weaver-worker   |     make_dirs(settings["weaver.wps_workdir"], exist_ok=True)
weaver-worker   |   File "/opt/local/src/weaver/weaver/utils.py", line 531, in make_dirs
weaver-worker   |     os.makedirs(path, mode=mode)
weaver-worker   |   File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
weaver-worker   |     mkdir(name, mode)
weaver-worker   | FileNotFoundError: [Errno 2] No such file or directory: ''
```
Its necessary follow the next steps to execute CWL?

1. /process
2. /process/{PROCESS_ID}/jobs
3. /process/{PROCESS_ID}/execution

Its possible has relationship with https://github.com/crim-ca/weaver/issues/275?

Thanks!

**Comment by fmigneault** [comment] 2021-09-02 18:41
@pedringcoding 
The error with `POST /process/{PROCESS_ID}/execution` seems like an incorrect config. The app doesn't find it. 
It will be patched in a next release. 
In the meantime, you can use `POST /process/{PROCESS_ID}/jobs`. It is 100% an alias of the execution path.

You can look at `http://localhost:4001/processes/HELLOWORLD/jobs/95291ce5-2ac8-4558-a0ca-d16ebe36c08a/logs` to see if there are any more details about the processing errors. 

My first guess would be that you got `weaver.wps_workdir = ''` in your INI config. It needs to be a directory path, either only local within the docker, or volume mounted one if you want to keep intermediate results between up/down of the dockers.

**Comment by fmigneault** [comment] 2021-09-16 05:09
Closing as fixed by https://github.com/crim-ca/weaver/issues/290#issuecomment-919929452

**Closed by fmigneault** 2021-09-16 05:09 UTC
Labels: triage/bug
